apiVersion: v2
name: calcom
description: Deploy Calcom in a Helm Chart
type: application
version: 0.6.6
appVersion: v4.2.5
keywords:
  - kubernetes
  - chart
  - schedule
  - conference
  - calendar
  - visio
  - helm
  - meeting
  - cal
  - appointment
  - calcom
sources:
  - https://github.com/Pyrrha/calcom-helm
home: https://pyrrha.github.io/calcom-helm/
maintainers:
  - name: Pyrrha
    url: https://github.com/Pyrrha/calcom-helm
