apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calcom.fullname" . }}
  labels:
    {{- include "calcom.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calcom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calcom.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- $secretRef  := .Values.secretRef -}}
            {{- range tuple "DATABASE_URL" "NEXT_PUBLIC_WEBAPP_URL" "NEXTAUTH_SECRET" "CALENDSO_ENCRYPTION_KEY" }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  key: {{ . }}
                  name: {{ $secretRef }}
            {{- end}}
            - name: DATABASE_DIRECT_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: {{ .Values.secretRef }}
            {{- range tuple "CALCOM_LICENSE_KEY" "UPSTASH_REDIS_REST_URL" "UPSTASH_REDIS_REST_TOKEN" "INSIGHTS_DATABASE_URL" "PRISMA_GENERATE_DATAPROXY" "NEXT_PUBLIC_WEBAPP_URL" "NEXT_PUBLIC_WEBSITE_URL" "NEXT_PUBLIC_CONSOLE_URL" "NEXT_PUBLIC_EMBED_LIB_URL" "SAML_DATABASE_URL" "SAML_ADMINS" "NEXT_PUBLIC_HOSTED_CAL_FEATURES" "SAML_CLIENT_SECRET_VERIFIER" "PGSSLMODE" "ALLOWED_HOSTNAMES" "RESERVED_SUBDOMAINS" "NEXTAUTH_URL" "NEXTAUTH_SECRET" "NEXTAUTH_COOKIE_DOMAIN" "CALCOM_TELEMETRY_DISABLED" "CRON_API_KEY" "CRON_ENABLE_APP_SYNC" "CALENDSO_ENCRYPTION_KEY" "NEXT_PUBLIC_INTERCOM_APP_ID" "INTERCOM_SECRET" "NEXT_PUBLIC_ZENDESK_KEY" "NEXT_PUBLIC_HELPSCOUT_KEY" "NEXT_PUBLIC_FRESHCHAT_TOKEN" "NEXT_PUBLIC_FRESHCHAT_HOST" "GOOGLE_LOGIN_ENABLED" "GOOGLE_API_CREDENTIALS" "SEND_FEEDBACK_EMAIL" "SENDGRID_API_KEY" "SENDGRID_EMAIL" "NEXT_PUBLIC_SENDGRID_SENDER_NAME" "NEXT_PUBLIC_SENTRY_DSN" "NEXT_PUBLIC_FORMBRICKS_HOST_URL" "NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID" "FORMBRICKS_FEEDBACK_SURVEY_ID" "AVATARAPI_USERNAME" "AVATARAPI_PASSWORD" "TWILIO_SID" "TWILIO_TOKEN" "TWILIO_MESSAGING_SID" "TWILIO_PHONE_NUMBER" "TWILIO_WHATSAPP_PHONE_NUMBER" "NEXT_PUBLIC_SENDER_ID" "TWILIO_VERIFY_SID" "NEXT_PUBLIC_IS_E2E" "NEXT_PUBLIC_STRIPE_PRO_PLAN_PRICE" "NEXT_PUBLIC_STRIPE_PREMIUM_PLAN_PRICE" "NEXT_PUBLIC_IS_PREMIUM_NEW_PLAN" "NEXT_PUBLIC_STRIPE_PREMIUM_NEW_PLAN_PRICE" "STRIPE_TEAM_MONTHLY_PRICE_ID" "STRIPE_ORG_MONTHLY_PRICE_ID" "STRIPE_WEBHOOK_SECRET" "STRIPE_WEBHOOK_SECRET_APPS" "STRIPE_PRIVATE_KEY" "STRIPE_CLIENT_ID" "PAYMENT_FEE_FIXED" "PAYMENT_FEE_PERCENTAGE" "API_KEY_PREFIX" "EMAIL_FROM" "EMAIL_SERVER_HOST" "EMAIL_SERVER_PORT" "E2E_TEST_MAILHOG_ENABLED" "NEXT_PUBLIC_TEAM_IMPERSONATION" "CLOSECOM_API_KEY" "SENDGRID_SYNC_API_KEY" "NEXT_PUBLIC_APP_NAME" "NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS" "NEXT_PUBLIC_COMPANY_NAME" "NEXT_PUBLIC_DISABLE_SIGNUP" "CSP_POLICY" "EDGE_CONFIG" "NEXT_PUBLIC_MINUTES_TO_BOOK" "NEXT_PUBLIC_BOOKER_NUMBER_OF_DAYS_TO_LOAD" "NEXT_PUBLIC_AVAILABILITY_SCHEDULE_INTERVAL" "ORGANIZATIONS_ENABLED" "ORGANIZATIONS_AUTOLINK" "PROJECT_ID_VERCEL" "TEAM_ID_VERCEL" "AUTH_BEARER_TOKEN_VERCEL" "E2E_TEST_APPLE_CALENDAR_EMAIL" "E2E_TEST_APPLE_CALENDAR_PASSWORD" "E2E_TEST_CALCOM_QA_EMAIL" "E2E_TEST_CALCOM_QA_PASSWORD" "E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS" "E2E_TEST_CALCOM_GCAL_KEYS" "CALCOM_CREDENTIAL_SYNC_SECRET" "CALCOM_CREDENTIAL_SYNC_HEADER_NAME" "CALCOM_CREDENTIAL_SYNC_ENDPOINT" "CALCOM_APP_CREDENTIAL_ENCRYPTION_KEY" "E2E_TEST_SAML_ADMIN_EMAIL" "E2E_TEST_SAML_ADMIN_PASSWORD" "E2E_TEST_OIDC_CLIENT_ID" "E2E_TEST_OIDC_CLIENT_SECRET" "E2E_TEST_OIDC_PROVIDER_DOMAIN" "E2E_TEST_OIDC_USER_EMAIL" "E2E_TEST_OIDC_USER_PASSWORD" "AB_TEST_BUCKET_PROBABILITY" "APP_ROUTER_EVENT_TYPES_ENABLED" "APP_ROUTER_SETTINGS_ADMIN_ENABLED" "APP_ROUTER_APPS_INSTALLED_CATEGORY_ENABLED" "APP_ROUTER_APPS_SLUG_ENABLED" "APP_ROUTER_APPS_SLUG_SETUP_ENABLED" "APP_ROUTER_APPS_CATEGORIES_ENABLED" "APP_ROUTER_APPS_CATEGORIES_CATEGORY_ENABLED" "APP_ROUTER_BOOKINGS_STATUS_ENABLED" "APP_ROUTER_WORKFLOWS_ENABLED" "APP_ROUTER_SETTINGS_TEAMS_ENABLED" "APP_ROUTER_GETTING_STARTED_STEP_ENABLED" "APP_ROUTER_APPS_ENABLED" "APP_ROUTER_VIDEO_ENABLED" "APP_ROUTER_TEAMS_ENABLED" "SENTRY_DISABLE_SERVER_WEBPACK_PLUGIN" "NEXT_PUBLIC_API_V2_URL" "MS_GRAPH_CLIENT_ID" "MS_GRAPH_CLIENT_SECRET" }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  key: {{ . }}
                  name: {{ $secretRef }}
                  optional: true
            {{- end}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
